# -*- coding: utf-8 -*-
"""CIE 1

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YB5IMP2VG0Vvc5SRwZDlJXuZVyNCXdFM
"""

import pandas as pd
data = pd.read_csv("/content/mtcars.csv")
print(data)

import matplotlib.pyplot as plt
plt.hist(data['mpg'], bins=10, color='lightblue', edgecolor='black')
plt.title('Frequency Distribution of Miles per Gallon (mpg)')
plt.xlabel('Miles per Gallon (mpg)')
plt.ylabel('Frequency')
plt.grid()
plt.show()

import matplotlib.pyplot as plt
plt.scatter(data['wt'], data['mpg'], color='g', alpha=0.7)
plt.title('Relationship between Car Weight and MPG')
plt.xlabel('Weight of the Car')
plt.ylabel('Miles per Gallon (MPG)')
plt.grid(True)
plt.show()

import matplotlib.pyplot as plt
tc = data.groupby('manufacturer').size().nlargest(5)
tc.plot(kind='bar', color='blue')
plt.title('Frequency Distribution of Transmission Types')
plt.xlabel('types of cars')
plt.ylabel('Frequency')
plt.show()

import matplotlib.pyplot as plt
data.boxplot(column='mpg', by='cyl', grid=False, color='r')
plt.title('Box and Whisker Plot of MPG by Cylinder Count')
plt.xlabel('Number of Cylinders')
plt.ylabel('Miles per Gallon (MPG)')
plt.show()